model:
  model_class_path: model.rwkv7_backbone.RWKV7BackboneForCausalLM
  token_mixer: gptalpha
  vocab_size: 50304
  num_hidden_layers: 12
  num_attention_heads: 6
  hidden_size: 768
  ffn_expansion: 4
  use_skip_connections: 0
  use_block_lambdas: 0
  logit_softcap: 0
  use_l2wrap: 0
  use_tokenshift_att: 1
  use_tokenshift_ffn: 1
  rope_partial_dim: 64
  residual_scale: 1.0
