train:
  warmup_iters: 200
  warmdown_type: linear
  num_iterations: 30000
  val_loss_every: 1250
  warmdown_iters: 29800
  warmdown_min_ratio: 0.0
  optimizer_defaults:
    adam:
      name: adam
      args:
        lr: 8.94427e-4
        beta1: 0.9
        beta2: 0.95
        weight_decay: 8.94427e-2
